pub const REQUEST_SUBEVENTS: &[&str] = &["request.open", "request.body_in", "request.chunk_in", "request.accept", "request.close", "request.disconnect", "response.open", "response.body_out", "response.chunk_out", "response.close", "response.emit_complete"];

pub const PROTOCOLS: &[(&str, &str, &str, bool, &str)] = &[
    ("http.rest", "rest", "http", false, "http"),
    ("https.rest", "rest", "http", true, "http"),
    ("http.jsonrpc", "jsonrpc", "http", false, "http"),
    ("https.jsonrpc", "jsonrpc", "http", true, "http"),
    ("http.stream", "http.stream", "http", false, "http"),
    ("https.stream", "http.stream", "http", true, "http"),
    ("http.sse", "sse", "http", false, "http"),
    ("https.sse", "sse", "http", true, "http"),
    ("ws", "websocket", "websocket", false, "websocket"),
    ("wss", "websocket", "websocket", true, "websocket"),
    ("webtransport", "webtransport", "webtransport", true, "webtransport"),
    ("asgi.pathsend", "http.stream", "http", false, "http"),
];

pub const AUTOMATA_TRANSITIONS: &[(&str, &str, &str, &str)] = &[
    ("request", "idle", "request.open", "open"),
    ("request", "open", "request.body_in", "open"),
    ("request", "open", "request.chunk_in", "open"),
    ("request", "open", "request.accept", "accepted"),
    ("request", "accepted", "response.open", "responding"),
    ("request", "responding", "response.body_out", "responding"),
    ("request", "responding", "response.chunk_out", "responding"),
    ("request", "responding", "response.emit_complete", "completing"),
    ("request", "completing", "response.close", "closed"),
    ("request", "open", "request.disconnect", "disconnected"),
    ("session", "idle", "session.open", "open"),
    ("session", "open", "session.accept", "accepted"),
    ("session", "accepted", "session.ready", "ready"),
    ("session", "ready", "session.heartbeat", "ready"),
    ("session", "ready", "session.sync", "ready"),
    ("session", "ready", "session.emit_complete", "ready"),
    ("session", "ready", "session.close", "closed"),
    ("session", "ready", "session.disconnect", "disconnected"),
    ("message", "idle", "message.in", "received"),
    ("message", "received", "message.decode", "decoded"),
    ("message", "decoded", "message.handle", "handled"),
    ("message", "handled", "message.out", "emitted"),
    ("message", "emitted", "message.ack", "complete"),
    ("message", "emitted", "message.nack", "rejected"),
    ("message", "complete", "message.replay", "emitted"),
    ("message", "complete", "message.snapshot", "complete"),
    ("message", "emitted", "message.emit_complete", "complete"),
    ("stream", "idle", "stream.open", "open"),
    ("stream", "open", "stream.chunk_in", "open"),
    ("stream", "open", "stream.chunk_out", "open"),
    ("stream", "open", "stream.flush", "open"),
    ("stream", "open", "stream.finalize", "finalizing"),
    ("stream", "finalizing", "stream.emit_complete", "closed"),
    ("stream", "open", "stream.close", "closed"),
    ("stream", "open", "stream.abort", "aborted"),
    ("datagram", "idle", "datagram.in", "received"),
    ("datagram", "received", "datagram.handle", "handled"),
    ("datagram", "handled", "datagram.out", "emitted"),
    ("datagram", "emitted", "datagram.ack", "acknowledged"),
    ("datagram", "acknowledged", "datagram.emit_complete", "acknowledged"),
    ("datagram", "acknowledged", "datagram.close", "closed"),
];
