BINDING_FAMILY_MATRIX = {
  "rest": {
    "request": "R",
    "session": "F",
    "message": "F",
    "stream": "O",
    "datagram": "F",
    "lifespan": "F"
  },
  "jsonrpc": {
    "request": "R",
    "session": "F",
    "message": "F",
    "stream": "O",
    "datagram": "F",
    "lifespan": "F"
  },
  "http.stream": {
    "request": "R",
    "session": "F",
    "message": "F",
    "stream": "R",
    "datagram": "F",
    "lifespan": "F"
  },
  "sse": {
    "request": "R",
    "session": "R",
    "message": "R",
    "stream": "R",
    "datagram": "F",
    "lifespan": "F"
  },
  "websocket": {
    "request": "F",
    "session": "R",
    "message": "R",
    "stream": "F",
    "datagram": "F",
    "lifespan": "F"
  },
  "webtransport": {
    "request": "F",
    "session": "R",
    "message": "O",
    "stream": "R",
    "datagram": "R",
    "lifespan": "F"
  }
}

FAMILY_SUBEVENT_MATRIX = {
  "request": {
    "request.open": "R",
    "request.body_in": "R",
    "request.chunk_in": "R",
    "request.dispatch": "R",
    "request.close": "R",
    "request.disconnect": "R",
    "response.open": "R",
    "response.body_out": "R",
    "response.chunk_out": "R",
    "response.finalize": "R",
    "response.emit_complete": "R"
  },
  "session": {
    "session.open": "R",
    "session.accept": "R",
    "session.reject": "R",
    "session.ready": "R",
    "session.heartbeat": "R",
    "session.sync": "R",
    "session.close": "R",
    "session.disconnect": "R",
    "session.emit_complete": "R"
  },
  "message": {
    "message.in": "R",
    "message.decode": "R",
    "message.decode_failed": "R",
    "message.handle": "R",
    "message.handle_failed": "R",
    "message.out": "R",
    "message.replay": "R",
    "message.snapshot": "R",
    "message.emit_complete": "R",
    "message.emit_failed": "R"
  },
  "stream": {
    "stream.open": "R",
    "stream.chunk_in": "R",
    "stream.chunk_out": "R",
    "stream.flush": "R",
    "stream.finalize": "R",
    "stream.reset": "R",
    "stream.stop_sending": "R",
    "stream.close": "R",
    "stream.emit_complete": "R"
  },
  "datagram": {
    "datagram.in": "R",
    "datagram.handle": "R",
    "datagram.out": "R",
    "datagram.emit_complete": "R",
    "datagram.emit_failed": "R"
  },
  "lifespan": {
    "lifespan.startup": "R",
    "lifespan.startup_complete": "R",
    "lifespan.startup_failed": "R",
    "lifespan.shutdown": "R",
    "lifespan.shutdown_complete": "R",
    "lifespan.shutdown_failed": "R"
  }
}

BINDING_SUBEVENT_MATRIX = {
  "rest": {
    "request.open": "R",
    "request.body_in": "R",
    "request.chunk_in": "F",
    "request.dispatch": "D",
    "request.close": "R",
    "request.disconnect": "O",
    "response.open": "R",
    "response.body_out": "R",
    "response.chunk_out": "F",
    "response.finalize": "O",
    "response.emit_complete": "R",
    "session.open": "F",
    "session.accept": "F",
    "session.reject": "F",
    "session.ready": "F",
    "session.heartbeat": "F",
    "session.sync": "F",
    "session.close": "F",
    "session.disconnect": "F",
    "session.emit_complete": "F",
    "message.in": "F",
    "message.decode": "F",
    "message.decode_failed": "F",
    "message.handle": "F",
    "message.handle_failed": "F",
    "message.out": "F",
    "message.replay": "F",
    "message.snapshot": "F",
    "message.emit_complete": "F",
    "message.emit_failed": "F",
    "stream.open": "O",
    "stream.chunk_in": "O",
    "stream.chunk_out": "O",
    "stream.flush": "F",
    "stream.finalize": "O",
    "stream.reset": "F",
    "stream.stop_sending": "F",
    "stream.close": "O",
    "stream.emit_complete": "O",
    "datagram.in": "F",
    "datagram.handle": "F",
    "datagram.out": "F",
    "datagram.emit_complete": "F",
    "datagram.emit_failed": "F",
    "lifespan.startup": "F",
    "lifespan.startup_complete": "F",
    "lifespan.startup_failed": "F",
    "lifespan.shutdown": "F",
    "lifespan.shutdown_complete": "F",
    "lifespan.shutdown_failed": "F"
  },
  "jsonrpc": {
    "request.open": "R",
    "request.body_in": "R",
    "request.chunk_in": "F",
    "request.dispatch": "D",
    "request.close": "R",
    "request.disconnect": "O",
    "response.open": "R",
    "response.body_out": "R",
    "response.chunk_out": "F",
    "response.finalize": "O",
    "response.emit_complete": "R",
    "session.open": "F",
    "session.accept": "F",
    "session.reject": "F",
    "session.ready": "F",
    "session.heartbeat": "F",
    "session.sync": "F",
    "session.close": "F",
    "session.disconnect": "F",
    "session.emit_complete": "F",
    "message.in": "F",
    "message.decode": "D",
    "message.decode_failed": "D",
    "message.handle": "F",
    "message.handle_failed": "F",
    "message.out": "F",
    "message.replay": "F",
    "message.snapshot": "F",
    "message.emit_complete": "F",
    "message.emit_failed": "F",
    "stream.open": "O",
    "stream.chunk_in": "O",
    "stream.chunk_out": "O",
    "stream.flush": "F",
    "stream.finalize": "O",
    "stream.reset": "F",
    "stream.stop_sending": "F",
    "stream.close": "O",
    "stream.emit_complete": "O",
    "datagram.in": "F",
    "datagram.handle": "F",
    "datagram.out": "F",
    "datagram.emit_complete": "F",
    "datagram.emit_failed": "F",
    "lifespan.startup": "F",
    "lifespan.startup_complete": "F",
    "lifespan.startup_failed": "F",
    "lifespan.shutdown": "F",
    "lifespan.shutdown_complete": "F",
    "lifespan.shutdown_failed": "F"
  },
  "http.stream": {
    "request.open": "R",
    "request.body_in": "O",
    "request.chunk_in": "D",
    "request.dispatch": "D",
    "request.close": "R",
    "request.disconnect": "O",
    "response.open": "R",
    "response.body_out": "O",
    "response.chunk_out": "D",
    "response.finalize": "O",
    "response.emit_complete": "R",
    "session.open": "F",
    "session.accept": "F",
    "session.reject": "F",
    "session.ready": "F",
    "session.heartbeat": "F",
    "session.sync": "F",
    "session.close": "F",
    "session.disconnect": "F",
    "session.emit_complete": "F",
    "message.in": "F",
    "message.decode": "F",
    "message.decode_failed": "F",
    "message.handle": "F",
    "message.handle_failed": "F",
    "message.out": "F",
    "message.replay": "F",
    "message.snapshot": "F",
    "message.emit_complete": "F",
    "message.emit_failed": "F",
    "stream.open": "R",
    "stream.chunk_in": "R",
    "stream.chunk_out": "R",
    "stream.flush": "O",
    "stream.finalize": "R",
    "stream.reset": "O",
    "stream.stop_sending": "F",
    "stream.close": "R",
    "stream.emit_complete": "R",
    "datagram.in": "F",
    "datagram.handle": "F",
    "datagram.out": "F",
    "datagram.emit_complete": "F",
    "datagram.emit_failed": "F",
    "lifespan.startup": "F",
    "lifespan.startup_complete": "F",
    "lifespan.startup_failed": "F",
    "lifespan.shutdown": "F",
    "lifespan.shutdown_complete": "F",
    "lifespan.shutdown_failed": "F"
  },
  "sse": {
    "request.open": "R",
    "request.body_in": "O",
    "request.chunk_in": "F",
    "request.dispatch": "D",
    "request.close": "R",
    "request.disconnect": "O",
    "response.open": "O",
    "response.body_out": "F",
    "response.chunk_out": "D",
    "response.finalize": "O",
    "response.emit_complete": "R",
    "session.open": "R",
    "session.accept": "R",
    "session.reject": "F",
    "session.ready": "R",
    "session.heartbeat": "O",
    "session.sync": "O",
    "session.close": "R",
    "session.disconnect": "O",
    "session.emit_complete": "O",
    "message.in": "F",
    "message.decode": "F",
    "message.decode_failed": "F",
    "message.handle": "F",
    "message.handle_failed": "F",
    "message.out": "R",
    "message.replay": "O",
    "message.snapshot": "O",
    "message.emit_complete": "R",
    "message.emit_failed": "O",
    "stream.open": "R",
    "stream.chunk_in": "F",
    "stream.chunk_out": "R",
    "stream.flush": "O",
    "stream.finalize": "O",
    "stream.reset": "O",
    "stream.stop_sending": "F",
    "stream.close": "R",
    "stream.emit_complete": "R",
    "datagram.in": "F",
    "datagram.handle": "F",
    "datagram.out": "F",
    "datagram.emit_complete": "F",
    "datagram.emit_failed": "F",
    "lifespan.startup": "F",
    "lifespan.startup_complete": "F",
    "lifespan.startup_failed": "F",
    "lifespan.shutdown": "F",
    "lifespan.shutdown_complete": "F",
    "lifespan.shutdown_failed": "F"
  },
  "websocket": {
    "request.open": "F",
    "request.body_in": "F",
    "request.chunk_in": "F",
    "request.dispatch": "F",
    "request.close": "F",
    "request.disconnect": "F",
    "response.open": "F",
    "response.body_out": "F",
    "response.chunk_out": "F",
    "response.finalize": "F",
    "response.emit_complete": "F",
    "session.open": "R",
    "session.accept": "R",
    "session.reject": "O",
    "session.ready": "R",
    "session.heartbeat": "O",
    "session.sync": "O",
    "session.close": "R",
    "session.disconnect": "O",
    "session.emit_complete": "O",
    "message.in": "R",
    "message.decode": "O",
    "message.decode_failed": "O",
    "message.handle": "R",
    "message.handle_failed": "O",
    "message.out": "R",
    "message.replay": "O",
    "message.snapshot": "O",
    "message.emit_complete": "R",
    "message.emit_failed": "O",
    "stream.open": "F",
    "stream.chunk_in": "F",
    "stream.chunk_out": "F",
    "stream.flush": "F",
    "stream.finalize": "F",
    "stream.reset": "F",
    "stream.stop_sending": "F",
    "stream.close": "F",
    "stream.emit_complete": "F",
    "datagram.in": "F",
    "datagram.handle": "F",
    "datagram.out": "F",
    "datagram.emit_complete": "F",
    "datagram.emit_failed": "F",
    "lifespan.startup": "F",
    "lifespan.startup_complete": "F",
    "lifespan.startup_failed": "F",
    "lifespan.shutdown": "F",
    "lifespan.shutdown_complete": "F",
    "lifespan.shutdown_failed": "F"
  },
  "webtransport": {
    "request.open": "F",
    "request.body_in": "F",
    "request.chunk_in": "F",
    "request.dispatch": "F",
    "request.close": "F",
    "request.disconnect": "F",
    "response.open": "F",
    "response.body_out": "F",
    "response.chunk_out": "F",
    "response.finalize": "F",
    "response.emit_complete": "F",
    "session.open": "R",
    "session.accept": "R",
    "session.reject": "O",
    "session.ready": "R",
    "session.heartbeat": "O",
    "session.sync": "O",
    "session.close": "R",
    "session.disconnect": "O",
    "session.emit_complete": "O",
    "message.in": "O",
    "message.decode": "O",
    "message.decode_failed": "O",
    "message.handle": "O",
    "message.handle_failed": "O",
    "message.out": "O",
    "message.replay": "O",
    "message.snapshot": "O",
    "message.emit_complete": "O",
    "message.emit_failed": "O",
    "stream.open": "R",
    "stream.chunk_in": "R",
    "stream.chunk_out": "R",
    "stream.flush": "O",
    "stream.finalize": "R",
    "stream.reset": "O",
    "stream.stop_sending": "O",
    "stream.close": "R",
    "stream.emit_complete": "R",
    "datagram.in": "R",
    "datagram.handle": "R",
    "datagram.out": "R",
    "datagram.emit_complete": "R",
    "datagram.emit_failed": "O",
    "lifespan.startup": "F",
    "lifespan.startup_complete": "F",
    "lifespan.startup_failed": "F",
    "lifespan.shutdown": "F",
    "lifespan.shutdown_complete": "F",
    "lifespan.shutdown_failed": "F"
  }
}

PROTOCOLS = {'asgi.pathsend': {'binding': 'http.stream',
                   'scope_type': 'http',
                   'secure': False,
                   'transport': 'http'},
 'http.jsonrpc': {'binding': 'jsonrpc',
                  'scope_type': 'http',
                  'secure': False,
                  'transport': 'http'},
 'http.rest': {'binding': 'rest',
               'scope_type': 'http',
               'secure': False,
               'transport': 'http'},
 'http.sse': {'binding': 'sse',
              'scope_type': 'http',
              'secure': False,
              'transport': 'http'},
 'http.stream': {'binding': 'http.stream',
                 'scope_type': 'http',
                 'secure': False,
                 'transport': 'http'},
 'https.jsonrpc': {'binding': 'jsonrpc',
                   'scope_type': 'http',
                   'secure': True,
                   'transport': 'http'},
 'https.rest': {'binding': 'rest',
                'scope_type': 'http',
                'secure': True,
                'transport': 'http'},
 'https.sse': {'binding': 'sse',
               'scope_type': 'http',
               'secure': True,
               'transport': 'http'},
 'https.stream': {'binding': 'http.stream',
                  'scope_type': 'http',
                  'secure': True,
                  'transport': 'http'},
 'webtransport': {'binding': 'webtransport',
                  'scope_type': 'webtransport',
                  'secure': True,
                  'transport': 'webtransport'},
 'ws': {'binding': 'websocket',
        'scope_type': 'websocket',
        'secure': False,
        'transport': 'websocket'},
 'wss': {'binding': 'websocket',
         'scope_type': 'websocket',
         'secure': True,
         'transport': 'websocket'}}

AUTOMATA = {'datagram': {'initial': 'idle',
              'terminal': ['complete', 'failed'],
              'transitions': [{'event': 'datagram.in',
                               'from': 'idle',
                               'to': 'received'},
                              {'event': 'datagram.handle',
                               'from': 'received',
                               'to': 'handled'},
                              {'event': 'datagram.out',
                               'from': 'handled',
                               'to': 'emitted'},
                              {'event': 'datagram.emit_complete',
                               'from': 'emitted',
                               'to': 'complete'},
                              {'event': 'datagram.emit_failed',
                               'from': 'emitted',
                               'to': 'failed'}]},
 'lifespan': {'initial': 'idle',
              'terminal': ['startup_complete',
                           'startup_failed',
                           'shutdown_complete',
                           'shutdown_failed'],
              'transitions': [{'event': 'lifespan.startup',
                               'from': 'idle',
                               'to': 'starting'},
                              {'event': 'lifespan.startup_complete',
                               'from': 'starting',
                               'to': 'startup_complete'},
                              {'event': 'lifespan.startup_failed',
                               'from': 'starting',
                               'to': 'startup_failed'},
                              {'event': 'lifespan.shutdown',
                               'from': 'startup_complete',
                               'to': 'shutting_down'},
                              {'event': 'lifespan.shutdown',
                               'from': 'idle',
                               'to': 'shutting_down'},
                              {'event': 'lifespan.shutdown_complete',
                               'from': 'shutting_down',
                               'to': 'shutdown_complete'},
                              {'event': 'lifespan.shutdown_failed',
                               'from': 'shutting_down',
                               'to': 'shutdown_failed'}]},
 'message': {'initial': 'idle',
             'terminal': ['complete', 'failed'],
             'transitions': [{'event': 'message.in',
                              'from': 'idle',
                              'to': 'received'},
                             {'event': 'message.decode',
                              'from': 'received',
                              'to': 'decoded'},
                             {'event': 'message.decode_failed',
                              'from': 'received',
                              'to': 'failed'},
                             {'event': 'message.handle',
                              'from': 'decoded',
                              'to': 'handled'},
                             {'event': 'message.handle_failed',
                              'from': 'decoded',
                              'to': 'failed'},
                             {'event': 'message.out',
                              'from': 'handled',
                              'to': 'emitted'},
                             {'event': 'message.emit_complete',
                              'from': 'emitted',
                              'to': 'complete'},
                             {'event': 'message.emit_failed',
                              'from': 'emitted',
                              'to': 'failed'},
                             {'event': 'message.replay',
                              'from': 'complete',
                              'to': 'emitted'},
                             {'event': 'message.snapshot',
                              'from': 'complete',
                              'to': 'complete'}]},
 'request': {'initial': 'idle',
             'terminal': ['closed', 'disconnected'],
             'transitions': [{'event': 'request.open',
                              'from': 'idle',
                              'to': 'open'},
                             {'event': 'request.body_in',
                              'from': 'open',
                              'to': 'open'},
                             {'event': 'request.chunk_in',
                              'from': 'open',
                              'to': 'open'},
                             {'event': 'request.close',
                              'from': 'open',
                              'to': 'body_closed'},
                             {'event': 'request.dispatch',
                              'from': 'open',
                              'to': 'dispatched'},
                             {'event': 'request.dispatch',
                              'from': 'body_closed',
                              'to': 'dispatched'},
                             {'event': 'response.open',
                              'from': 'dispatched',
                              'to': 'responding'},
                             {'event': 'response.body_out',
                              'from': 'responding',
                              'to': 'responding'},
                             {'event': 'response.chunk_out',
                              'from': 'responding',
                              'to': 'responding'},
                             {'event': 'response.emit_complete',
                              'from': 'responding',
                              'to': 'completing'},
                             {'event': 'response.finalize',
                              'from': 'completing',
                              'to': 'closed'},
                             {'event': 'request.disconnect',
                              'from': 'open',
                              'to': 'disconnected'},
                             {'event': 'request.disconnect',
                              'from': 'body_closed',
                              'to': 'disconnected'}]},
 'session': {'initial': 'idle',
             'terminal': ['closed', 'disconnected', 'rejected'],
             'transitions': [{'event': 'session.open',
                              'from': 'idle',
                              'to': 'open'},
                             {'event': 'session.accept',
                              'from': 'open',
                              'to': 'accepted'},
                             {'event': 'session.reject',
                              'from': 'open',
                              'to': 'rejected'},
                             {'event': 'session.disconnect',
                              'from': 'open',
                              'to': 'disconnected'},
                             {'event': 'session.ready',
                              'from': 'accepted',
                              'to': 'ready'},
                             {'event': 'session.disconnect',
                              'from': 'accepted',
                              'to': 'disconnected'},
                             {'event': 'session.heartbeat',
                              'from': 'ready',
                              'to': 'ready'},
                             {'event': 'session.sync',
                              'from': 'ready',
                              'to': 'ready'},
                             {'event': 'session.emit_complete',
                              'from': 'ready',
                              'to': 'ready'},
                             {'event': 'session.close',
                              'from': 'ready',
                              'to': 'closed'},
                             {'event': 'session.disconnect',
                              'from': 'ready',
                              'to': 'disconnected'}]},
 'stream': {'initial': 'idle',
            'terminal': ['closed', 'reset', 'stopped'],
            'transitions': [{'event': 'stream.open',
                             'from': 'idle',
                             'to': 'open'},
                            {'event': 'stream.chunk_in',
                             'from': 'open',
                             'to': 'open'},
                            {'event': 'stream.chunk_out',
                             'from': 'open',
                             'to': 'open'},
                            {'event': 'stream.flush',
                             'from': 'open',
                             'to': 'open'},
                            {'event': 'stream.finalize',
                             'from': 'open',
                             'to': 'finalizing'},
                            {'event': 'stream.emit_complete',
                             'from': 'finalizing',
                             'to': 'closed'},
                            {'event': 'stream.close',
                             'from': 'open',
                             'to': 'closed'},
                            {'event': 'stream.reset',
                             'from': 'open',
                             'to': 'reset'},
                            {'event': 'stream.stop_sending',
                             'from': 'open',
                             'to': 'stopped'},
                            {'event': 'stream.reset',
                             'from': 'finalizing',
                             'to': 'reset'},
                            {'event': 'stream.stop_sending',
                             'from': 'finalizing',
                             'to': 'stopped'}]}}

FRAMES = {'app': {'binding': 'webtransport', 'kind': 'contract-framing'},
 'asgi-pathsend-extension': {'binding': 'http.stream',
                             'kind': 'extension-frame'},
 'asgi-tls-extension': {'binding': '*', 'kind': 'extension-frame'},
 'bytes': {'binding': 'http.stream', 'kind': 'contract-framing'},
 'grpc': {'binding': 'http.stream', 'kind': 'contract-framing'},
 'http-1-1-message': {'binding': 'rest', 'kind': 'wire-frame'},
 'http-request-body-chunk': {'binding': 'http.stream', 'kind': 'wire-frame'},
 'http-response-body-chunk': {'binding': 'http.stream', 'kind': 'wire-frame'},
 'http-response-start-frame': {'binding': 'rest', 'kind': 'wire-frame'},
 'json': {'binding': 'rest', 'kind': 'contract-framing'},
 'json-rpc-error-object': {'binding': 'jsonrpc', 'kind': 'contract-framing'},
 'json-rpc-notification-object': {'binding': 'jsonrpc',
                                  'kind': 'contract-framing'},
 'json-rpc-request-object': {'binding': 'jsonrpc', 'kind': 'contract-framing'},
 'json-rpc-response-object': {'binding': 'jsonrpc', 'kind': 'contract-framing'},
 'jsonrpc': {'binding': 'jsonrpc', 'kind': 'contract-framing'},
 'raw': {'binding': 'websocket', 'kind': 'contract-framing'},
 'sse': {'binding': 'sse', 'kind': 'contract-framing'},
 'sse-data-field': {'binding': 'sse', 'kind': 'contract-framing'},
 'sse-event-field': {'binding': 'sse', 'kind': 'contract-framing'},
 'sse-id-field': {'binding': 'sse', 'kind': 'contract-framing'},
 'sse-retry-field': {'binding': 'sse', 'kind': 'contract-framing'},
 'websocket-accept-frame': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-close-frame': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-continuation-frame': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-disconnect-frame': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-frame': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-ping-frame': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-pong-frame': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-receive-bytes': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-receive-text': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-send-bytes': {'binding': 'websocket', 'kind': 'wire-frame'},
 'websocket-send-text': {'binding': 'websocket', 'kind': 'wire-frame'},
 'webtransport-datagram-frame': {'binding': 'webtransport',
                                 'kind': 'wire-frame'},
 'webtransport-stream-frame': {'binding': 'webtransport', 'kind': 'wire-frame'}}

EXTENSIONS = {'asgi.pathsend': {'event_type': 'http.response.pathsend',
                   'fields': {'headers': {'required': False, 'type': 'array'},
                              'path': {'required': True, 'type': 'string'},
                              'stat_result': {'required': False,
                                              'type': 'object'}}},
 'asgi.tls': {'fields': {'cipher': {'required': False, 'type': 'string'},
                         'peer_cert': {'required': False, 'type': 'object'},
                         'peer_identity': {'required': False, 'type': 'string'},
                         'verified': {'required': False, 'type': 'boolean'},
                         'version': {'required': False, 'type': 'string'}},
              'scope_key': 'tls'}}
